#!/system/bin/sh
#This option disable tweaks for PegasusQ governor
#restore tunables to default
#Default 800

echo 20000 > /sys/devices/system/cpu/cpufreq/pegasusq/sampling_rate
echo 20 > /sys/devices/system/cpu/cpufreq/pegasusq/cpu_up_rate
echo 40 > /sys/devices/system/cpu/cpufreq/pegasusq/cpu_down_rate
echo 500000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_1_1
echo 200000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_2_0
echo 600000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_2_1
echo 300000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_3_0
echo 700000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_3_1
echo 400000 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_freq_4_0
echo 150 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_1_1
echo 150 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_2_0
echo 300 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_2_1
echo 300 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_3_0
echo 400 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_3_1
echo 400 > /sys/devices/system/cpu/cpufreq/pegasusq/hotplug_rq_4_0
echo 2 > /sys/devices/system/cpu/cpufreq/pegasusq/sampling_down_factor
echo 37 > /sys/devices/system/cpu/cpufreq/pegasusq/freq_step

