#!/system/bin/sh
#Enable NOOP scheduler 
#WARNING: enable one option only!!
#Default 800

for i in `ls /sys/block/stl*` /sys/block/bml* /sys/block/mmcblk* /sys/block/mtdblock* ; do
        echo "noop" > $i/queue/scheduler;
        echo "$i/queue/scheduler";
done;
